version: '3.3'
services:
    web:
        command: ["bash", "app.sh"]
        restart: always

        image: gtato/sharelatex-web
        # build: sharelatex-web
        # container_name: sharelatex-web
        depends_on:
            - redis
            # - mongo
        privileged: true
        ports:
            - 8080:80
            - 3000:3000
        # volumes:
        #     - ~/sharelatex_data/web:/var/lib/mongodb
        environment:
            SHARELATEX_APP_NAME: MicroSharedLatex
            SHARELATEX_SESSION_SECRET: 'secret-please-change'
            SHARELATEX_CONFIG: /etc/sharelatex/settings.coffee
            SHARELATEX_SITE_URL: http://localhost:8080
            
            #these three are unnecessary 
            SHARELATEX_REAL_TIME_URL: http://real-time:3026
            SHARELATEX_REDIS_HOST: redis
            SHARELATEX_DOCUMENT_UPDATER_URL: http://document-updater:3003
    
            #centralized things 
            SHARELATEX_CLSI_URL: http://192.168.56.1:3013
            SHARELATEX_FILESTORE_URL: http://192.168.56.1:3009
            SHARELATEX_DOCSTORE_URL: http://192.168.56.1:3016
            SHARELATEX_SPELLING_URL: http://192.168.56.1:3005
            SHARELATEX_TAGS_URL: http://192.168.56.1:3012
            SHARELATEX_NOTIFICATIONS_URL: http://192.168.56.1:3042
            SHARELATEX_CONTACTS_URL: http://192.168.56.1:3036
            SHARELATEX_CHAT_URL: http://192.168.56.1:3010
            SHARELATEX_MONGO_URL: mongodb://192.168.56.1/sharelatex
       
       
        networks:
            default:
                aliases:
                    - web
      
    # clsi:
    #     restart: always
    #     image: gtato/sharelatex-clsi
    #     # build: sharelatex-clsi
    #     # container_name: sharelatex-clsi
    #     # expose:
    #     #     - 3013
    #     ports:
    #         - 3013:3013

        
    # spelling:
    #     restart: always
    #     image: gtato/sharelatex-spelling
    #     # build: sharelatex-spelling
    #     # container_name: sharelatex-spelling
    #     # expose:
    #     #     - 3005
    #     ports:
    #         - 3005:3005
    #     volumes:
    #         - ~/sharelatex_data/spelling:/var/lib/mongodb


    # chat:
    #     restart: always
    #     image: gtato/sharelatex-chat
    #     # build: sharelatex-chat
    #     # container_name: sharelatex-chat
    #     # expose:
    #     #     - 3010
    #     ports:
    #         - 3010:3010
    #     networks:
    #         default:
    #             aliases:
    #                 - chat
    #     volumes:
    #         - ~/sharelatex_data/chat:/var/lib/mongodb

    track-changes:
        restart: always
        image: gtato/sharelatex-track-changes
        ports:
            - 3015:3015
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - track-changes
        volumes:
            - ~/sharelatex_data/track_changes:/var/lib/mongodb

    real-time:
        restart: always
        image: gtato/sharelatex-real-time
        ports:
            - 3026:3026
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - real-time-core

    document-updater:
        restart: always
        image: gtato/sharelatex-document-updater
        ports:
            - 3003:3003
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - document-updater

    redis:
        restart: always
        image: redis
        ports:
            - 6379:6379
        networks:
            default:
                aliases:
                    - redis
        
networks:
    default:   
    