version: '3.3'
services:
    web:
        command: ["bash", "app.sh"]
        restart: always

        image: gtato/sharelatex-web
        build: sharelatex-web
        # container_name: sharelatex-web
        depends_on:
            - redis
            - mongo
        privileged: true
        ports:
            - 8080:80
            - 3000:3000
        # volumes:
        #     - ~/sharelatex_data/web:/var/lib/mongodb
        environment:
            SHARELATEX_REDIS_HOST: redis
            SHARELATEX_APP_NAME: MicroSharedLatex
            SHARELATEX_SESSION_SECRET: 'secret-please-change'
            SHARELATEX_CONFIG: /etc/sharelatex/settings.coffee
            SHARELATEX_SITE_URL: http://localhost:8080
            SHARELATEX_REAL_TIME_URL: http://real-time:3026
            SHARELATEX_REAL_TIME_ALT_URL: http://192.168.56.100:3026
            SHARELATEX_WEB_ALT_URL: http://192.168.56.100:8080
            PID: 5ab106cec2365e043f6923a5 #edge project
        networks:
            default:
                aliases:
                    - web
        # expose:
        #     - 3000
        # deploy:
        #     mode: global
            # endpoint_mode: dnsrr
      
    clsi:
        restart: always
        image: gtato/sharelatex-clsi
        build: sharelatex-clsi
        # container_name: sharelatex-clsi
        # expose:
        #     - 3013
        ports:
            - 3013:3013

    filestore:
        restart: always
        image: gtato/sharelatex-filestore
        build: sharelatex-filestore
        # container_name: sharelatex-filestore
        volumes:
            - ~/sharelatex_data/filestore:/app/data
        # expose:
        #     - 3009
        ports:
            - 3009:3009
        

    docstore:
        restart: always
        image: gtato/sharelatex-docstore
        build: sharelatex-docstore
        # container_name: sharelatex-docstore
        volumes:
            - ~/sharelatex_data/docstore:/var/lib/mongodb
        # expose:
        #     - 3016
        ports:
            - 3016:3016

    tags:
        restart: always
        build: sharelatex-tags
        image: gtato/sharelatex-tags
        # container_name: sharelatex-tags
        volumes:
            - ~/sharelatex_data/tags:/var/lib/mongodb
        # expose:
        #     - 3012
        ports:
            - 3012:3012

    notifications:
        restart: always
        image: gtato/sharelatex-notifications
        build: sharelatex-notifications
        # container_name: sharelatex-notifications
        volumes:
            - ~/sharelatex_data/notifications:/var/lib/mongodb
        # expose:
        #     - 3042
        ports:
            - 3042:3042

    contacts:
        restart: always
        image: gtato/sharelatex-contacts
        build: sharelatex-contacts
        # container_name: sharelatex-contacts
        volumes:
            - ~/sharelatex_data/contacts:/var/lib/mongodb
        # expose:
        #     - 3036
        ports:
            - 3036:3036
        
    spelling:
        restart: always
        image: gtato/sharelatex-spelling
        build: sharelatex-spelling
        # container_name: sharelatex-spelling
        # expose:
        #     - 3005
        ports:
            - 3005:3005
        volumes:
            - ~/sharelatex_data/spelling:/var/lib/mongodb


    chat:
        restart: always
        image: gtato/sharelatex-chat
        build: sharelatex-chat
        # container_name: sharelatex-chat
        # expose:
        #     - 3010
        ports:
            - 3010:3010
        networks:
            default:
                aliases:
                    - chat
        volumes:
            - ~/sharelatex_data/chat:/var/lib/mongodb

    track-changes:
        restart: always
        image: gtato/sharelatex-track-changes
        build: sharelatex-track-changes
        # container_name: sharelatex-track-changes
        # expose:
        #     - 3015
        ports:
            - 3015:3015
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - track-changes
        volumes:
            - ~/sharelatex_data/track_changes:/var/lib/mongodb

    real-time:
        restart: always
        image: gtato/sharelatex-real-time
        build: sharelatex-real-time
        # container_name: sharelatex-real-time
        # expose:
        #     - 3026
        ports:
            - 3026:3026
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - real-time-core
        # deploy:
        #     placement:
        #         constraints:
        #             - node.role == manager

    # real-time-edge:
    #     restart: always
    #     image: gtato/sharelatex-real-time
    #     build: sharelatex-real-time
    #     # container_name: sharelatex-real-time
    #     expose:
    #         - 3026
    #     depends_on:
    #         - redis
    #     networks:
    #         default:
    #             aliases:
    #                 - real-time-edge
    #     deploy:
    #         placement:
    #             constraints:
    #                 - node.role == worker


    document-updater:
        restart: always
        image: gtato/sharelatex-document-updater
        build: sharelatex-document-updater
        # expose:
        #     - 3003
        ports:
            - 3003:3003
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - document-updater
        # deploy:
        #     replicas: 1
        # volumes:
        #     - ~/sharelatex_data/document_updater:/var/lib/mongodb

    mongo:
        restart: always
        image: mongo
        # container_name: mongo
        # expose:
        #     - 27017
        ports:
            - 27017:27017
        volumes:
            - ~/mongo_data:/data/db

    redis:
        restart: always
        image: redis
        # container_name: redis
        # expose:
        #     - 6379
        ports:
            - 6379:6379
        # volumes:
        #     - ~/redis_data:/data
        networks:
            default:
                aliases:
                    - redis
        # deploy:
        #     replicas: 1
    

    redis-syncer:
        restart: always
        image: gtato/sharelatex-redis-syncer
        build: sharelatex-redis-syncer
        depends_on:
            - redis
        environment:
            REDIS_HOSTS: '192.168.56.1,192.168.56.100'
            REDIS_TIMEOUT: 500


networks:
    default:   
    
# nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       #- "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - /home/sharelatex/tmp:/etc/nginx/certs
