version: '3.3'
services:
    web:
        command: ["bash", "app.sh"]
        restart: always

        image: gtato/sharelatex-web
        #build: sharelatex-web
        # container_name: sharelatex-web
        depends_on:
            - redis
            - mongo
        privileged: true
        ports:
            - 8080:80
            - 3000:3000
        # volumes:
        #     - ~/sharelatex_data/web:/var/lib/mongodb
        environment:
            SHARELATEX_REDIS_HOST: redis
            SHARELATEX_APP_NAME: MicroSharedLatex
            SHARELATEX_SESSION_SECRET: 'secret-please-change'
            SHARELATEX_CONFIG: /etc/sharelatex/settings.coffee
            SHARELATEX_SITE_URL: "http://localhost:8080/"
            NGINX_CONFIG: "KOALA" #this should work for consul as well

            # KOALA: "http://192.168.56.1:8008/api/get"

            SHARELATEX_SPELLING_URL: "${CONSUL_API}/sharelatex-spelling"
            SHARELATEX_TAGS_URL: "${CONSUL_API}/sharelatex-tags"
            SHARELATEX_CONTACTS_URL: "${CONSUL_API}/sharelatex-contacts"
            SHARELATEX_NOTIFICATIONS_URL: "${CONSUL_API}/sharelatex-notifications"
            SHARELATEX_CHAT_URL: "${CONSUL_API}/sharelatex-chat"
            SHARELATEX_FILESTORE_URL: "${CONSUL_API}/sharelatex-filestore"
            SHARELATEX_DOCSTORE_URL: "${CONSUL_API}/sharelatex-docstore"
            SHARELATEX_CLSI_URL: "${CONSUL_API}/sharelatex-clsi"

            SHARELATEX_DOCUMENT_UPDATER_URL: "${CONSUL_API}/sharelatex-document-updater"
            SHARELATEX_REAL_TIME_URL: "${CONSUL_API}/sharelatex-real-time"
            SHARELATEX_TRACK_CHANGES_URL: "${CONSUL_API}/sharelatex-track-changes"

            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-80"
            SHARELATEX_MONGO_URL: mongodb://${CORE_IP}/sharelatex

        networks:
            default:
                aliases:
                    - web

      
    clsi:
        restart: always
        image: gtato/sharelatex-clsi
        depends_on:
            - registrator
        ports:
            - 3013:3013

         
    spelling:
        restart: always
        image: gtato/sharelatex-spelling
        #build: sharelatex-spelling
        ports:
            - 3005:3005
        volumes:
            - ~/sharelatex_data/spelling:/var/lib/mongodb
        depends_on:
            - registrator


    chat:
        restart: always
        image: gtato/sharelatex-chat
        #build: sharelatex-chat
        ports:
            - 3010:3010
        networks:
            default:
                aliases:
                    - chat
        volumes:
            - ~/sharelatex_data/chat:/var/lib/mongodb
        depends_on:
            - registrator

    track-changes:
        restart: always
        image: gtato/sharelatex-track-changes
        #build: sharelatex-track-changes
        ports:
            - 3015:3015
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - track-changes
        volumes:
            - ~/sharelatex_data/track_changes:/var/lib/mongodb
        environment:
            SHARELATEX_DOCUMENT_UPDATER_URL: "${CONSUL_API}/sharelatex-document-updater"
            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-3000"


    real-time:
        restart: always
        image: gtato/sharelatex-real-time
        ports:
            - 3026:3026
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - real-time-core
        environment:
            SHARELATEX_DOCUMENT_UPDATER_URL: "${CONSUL_API}/sharelatex-document-updater"
            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-3000"


    document-updater:
        restart: always
        image: gtato/sharelatex-document-updater
        #build: sharelatex-document-updater
        # expose:
        #     - 3003
        ports:
            - 3003:3003
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - document-updater
        environment:
            SHARELATEX_TRACK_CHANGES_URL: "${CONSUL_API}/sharelatex-track-changes"
            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-3000"

    registrator:
        command: "-internal=true consul://consul:8500"
        image: gliderlabs/registrator:latest
        container_name: registrator
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        depends_on:
            - consul

    consul:
        image: consul:latest
        command: "agent -server -bootstrap -datacenter dc1 -node server1 -ui -client 0.0.0.0 "
        ports:
          - "8300:8300"
          - "8400:8400"
          - "8500:8500"
          - "8600:53/udp"
        depends_on:
            - redis-syncer

    consul-proxy:
        image: gtato/consul-proxy
        command: "node consul-proxy.js" 
        privileged: true
        ports:
            - 8700:8700
        networks:
            default:
                aliases:
                    - consul-proxy
        # environment:
        #    SYNCER_URL: "http://${CORE_IP}:8006"
        #    CONSUL_URL: "http://${CORE_IP}:8500"
        #    PROXY_URL: "http://${CORE_IP}:8700"
        depends_on:
            - consul
            - redis 

    redis:
        restart: always
        image: redis
        ports:
            - 6379:6379
        # volumes:
        #     - ~/redis_data:/data
        networks:
            default:
                aliases:
                    - redis
        depends_on:
            - registrator

    redis-syncer:
        restart: always
        image: gtato/sharelatex-redis-syncer
        #build: sharelatex-redis-syncer
        ports:
            - 8006:8006
        # environment:
        #     REDIS_HOSTS: '192.168.56.1,192.168.56.100'
        #     REDIS_TIMEOUT: 500


networks:
    default:   
    
# nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       #- "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - /home/sharelatex/tmp:/etc/nginx/certs
