version: '3.3'
services:
    web:
        command: ["bash", "app.sh"]
        restart: always

        image: gtato/sharelatex-web
        #build: sharelatex-web
        # container_name: sharelatex-web
        depends_on:
            - redis
            - mongo
        privileged: true
        ports:
            - 8080:80
            - 3000:3000
        # volumes:
        #     - ~/sharelatex_data/web:/var/lib/mongodb
        environment:
            SHARELATEX_REDIS_HOST: redis
            SHARELATEX_APP_NAME: MicroSharedLatex
            SHARELATEX_SESSION_SECRET: 'secret-please-change'
            SHARELATEX_CONFIG: /etc/sharelatex/settings.coffee
            SHARELATEX_SITE_URL: "http://localhost:8080/"
            NGINX_CONFIG: "KOALA" #this should work for consul as well

            # KOALA: "http://192.168.56.1:8008/api/get"

            SHARELATEX_SPELLING_URL: "${CONSUL_API}/sharelatex-spelling"
            SHARELATEX_TAGS_URL: "${CONSUL_API}/sharelatex-tags"
            SHARELATEX_CONTACTS_URL: "${CONSUL_API}/sharelatex-contacts"
            SHARELATEX_NOTIFICATIONS_URL: "${CONSUL_API}/sharelatex-notifications"
            SHARELATEX_CHAT_URL: "${CONSUL_API}/sharelatex-chat"
            SHARELATEX_FILESTORE_URL: "${CONSUL_API}/sharelatex-filestore"
            SHARELATEX_DOCSTORE_URL: "${CONSUL_API}/sharelatex-docstore"
            SHARELATEX_CLSI_URL: "${CONSUL_API}/sharelatex-clsi"

            SHARELATEX_DOCUMENT_UPDATER_URL: "${CONSUL_API}/sharelatex-document-updater"
            SHARELATEX_REAL_TIME_URL: "${CONSUL_API}/sharelatex-real-time"
            SHARELATEX_TRACK_CHANGES_URL: "${CONSUL_API}/sharelatex-track-changes"

            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-80"
        networks:
            default:
                aliases:
                    - web

      
    clsi:
        restart: always
        image: gtato/sharelatex-clsi
        #build: sharelatex-clsi
        # container_name: sharelatex-clsi
        # expose:
        #     - 3013
        depends_on:
            - registrator
        ports:
            - 3013:3013

    filestore:
        restart: always
        image: gtato/sharelatex-filestore
        #build: sharelatex-filestore
        volumes:
            - ~/sharelatex_data/filestore:/app/data
        depends_on:
            - registrator
        ports:
            - 3009:3009
        

    docstore:
        restart: always
        image: gtato/sharelatex-docstore
        #build: sharelatex-docstore
        volumes:
            - ~/sharelatex_data/docstore:/var/lib/mongodb
        ports:
            - 3016:3016
        depends_on:
            - registrator

    tags:
        restart: always
        #build: sharelatex-tags
        image: gtato/sharelatex-tags
        volumes:
            - ~/sharelatex_data/tags:/var/lib/mongodb
        ports:
            - 3012:3012
        depends_on:
            - registrator

    notifications:
        restart: always
        image: gtato/sharelatex-notifications
        #build: sharelatex-notifications
        volumes:
            - ~/sharelatex_data/notifications:/var/lib/mongodb
        ports:
            - 3042:3042
        depends_on:
            - registrator

    contacts:
        restart: always
        image: gtato/sharelatex-contacts
        #build: sharelatex-contacts
        volumes:
            - ~/sharelatex_data/contacts:/var/lib/mongodb
        ports:
            - 3036:3036
        depends_on:
            - registrator
        
    spelling:
        restart: always
        image: gtato/sharelatex-spelling
        #build: sharelatex-spelling
        ports:
            - 3005:3005
        volumes:
            - ~/sharelatex_data/spelling:/var/lib/mongodb
        depends_on:
            - registrator


    chat:
        restart: always
        image: gtato/sharelatex-chat
        #build: sharelatex-chat
        ports:
            - 3010:3010
        networks:
            default:
                aliases:
                    - chat
        volumes:
            - ~/sharelatex_data/chat:/var/lib/mongodb
        depends_on:
            - registrator

    track-changes:
        restart: always
        image: gtato/sharelatex-track-changes
        #build: sharelatex-track-changes
        ports:
            - 3015:3015
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - track-changes
        volumes:
            - ~/sharelatex_data/track_changes:/var/lib/mongodb
        environment:
            SHARELATEX_DOCUMENT_UPDATER_URL: "${CONSUL_API}/sharelatex-document-updater"
            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-3000"


    real-time:
        restart: always
        image: gtato/sharelatex-real-time
        #build: sharelatex-real-time
        # container_name: sharelatex-real-time
        # expose:
        #     - 3026
        ports:
            - 3026:3026
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - real-time-core
        environment:
            SHARELATEX_DOCUMENT_UPDATER_URL: "${CONSUL_API}/sharelatex-document-updater"
            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-3000"


    document-updater:
        restart: always
        image: gtato/sharelatex-document-updater
        #build: sharelatex-document-updater
        # expose:
        #     - 3003
        ports:
            - 3003:3003
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - document-updater
        environment:
            SHARELATEX_TRACK_CHANGES_URL: "${CONSUL_API}/sharelatex-track-changes"
            SHARELATEX_WEB_URL: "${CONSUL_API}/sharelatex-web-3000"

    registrator:
        command: "-internal=true consul://consul:8500"
        image: gliderlabs/registrator:latest
        container_name: registrator
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        depends_on:
            - consul

    # registrator:
    #     command: "/bin/registrator -internal=true koala://172.17.0.1:8008"
    #     image: gtato/registrator
    #     # dockcontainer_name: registrator
    #     volumes:
    #         - "/var/run/docker.sock:/tmp/docker.sock"
    #     depends_on: 
    #         # - redis-syncer
    #         - koala

    consul:
        image: consul:latest
        command: "agent -server -bootstrap -datacenter dc1 -node server1 -ui -client 0.0.0.0 "
        ports:
          - "8300:8300"
          - "8400:8400"
          - "8500:8500"
          - "8600:53/udp"
        depends_on:
            - redis-syncer

    # consul-proxy:
    #     image: gtato/consul-proxy
    #     command: "nodemon consul-proxy.js" 
    #     privileged: true
    #     ports:
    #         - 8700:8700
    #     networks:
    #         default:
    #             aliases:
    #                 - consul-proxy
    #     environment:
    #        SYNCER_URL: "http://${CORE_IP}:8006"
    #        CONSUL_URL: "http://${CORE_IP}:8500"
    #        PROXY_URL: "http://${CORE_IP}:8700"
    #     depends_on:
    #         - consul

    mongo:
        restart: always
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ~/mongo_data:/data/db

    redis:
        restart: always
        image: redis
        ports:
            - 6379:6379
        # volumes:
        #     - ~/redis_data:/data
        networks:
            default:
                aliases:
                    - redis
        depends_on:
            - registrator

    redis-syncer:
        restart: always
        image: gtato/sharelatex-redis-syncer
        #build: sharelatex-redis-syncer
        ports:
            - 8006:8006
        # environment:
        #     REDIS_HOSTS: '192.168.56.1,192.168.56.100'
        #     REDIS_TIMEOUT: 500


networks:
    default:   
    
# nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       #- "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - /home/sharelatex/tmp:/etc/nginx/certs
